---

- name: Install CIFS and other required packages for mounting
  package:
     name: "{{ item }}"
     state: present
  with_items: "{{ apt_mount_packages }}"

- name: Create credentials File for SMB share
  blockinfile:
    path: /root/.smbcred
    create: yes
    mode: 400
    owner: root
    group: root
    block: |
      username={{ share_user }}
      password={{ vault_share_password }}

- name: ensure devices mounted
  mount:
    name: '{{ item.name }}'
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts  | default("defaults") }}'
    state: '{{ item.state  | default("mounted")  }}'
    dump: '{{ item.dump | default("0") }}'
    passno: '{{ item.passno | default("0") }}'
    fstab: '{{ item.fstab | default("/etc/fstab") }}'
  with_items: '{{ mount_devices }}'
